language: node_js
node_js:
  - 12

cache: npm

before_script:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

script:
  - npm test
  - npx codechecks
  - npx truffle run coverage
  - cat coverage/lcov.info | npx coveralls
